# Generated by Django 2.2.16 on 2022-10-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
