# Generated by Django 2.2.16 on 2022-10-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20221018_2138'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='not_equal',
        ),
    ]
